FROM alpine
RUN apk add --no-cache nodejs yarn
RUN apk add --no-cache openjdk8
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"
RUN apk add --no-cache py-pip
RUN apk add --no-cache python3
RUN mkdir code
WORKDIR '/code'
COPY . .
RUN pip install -r requirements.txt
CMD ["python","engine.py"]